### PR TITLE
Fix parsing of exashare links w/o captions

### PR DESCRIPTION
**Pull request by jose1711**
This change is [Reviewable](https://reviewable.io/reviews/kodi-czsk/script.module.stream.resolver/34)

### CODE REVIEW

**Comment by jose1711** [comment]
fix for exashare parser

**Comment by lubo** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

_[lib/server/exashareresolver.py, line 46 [r1]](https://reviewable.io:443/reviews/kodi-czsk/script.module.stream.resolver/34#-KNSnLHROjWmYrw1dbeP:-KNSnLHSr3DkkENKO4wS:-854698943) ([raw file](https://github.com/kodi-czsk/script.module.stream.resolver/blob/d6f5cb22c82cab1a21a5367571b73632fe74e62a/lib/server/exashareresolver.py#L46)):_

> ``` Python
>             for source in data['sources']:           
>                 if 'tracks' in data:                                                        
>                     if data['tracks']:
> ```

These two `if` statements can be merge into a single one.

---

_[lib/server/exashareresolver.py, line 54 [r1]](https://reviewable.io:443/reviews/kodi-czsk/script.module.stream.resolver/34#-KNSnYfbv7xuJw9wqNJs:-KNSnYfbv7xuJw9wqNJt:-1291650804) ([raw file](https://github.com/kodi-czsk/script.module.stream.resolver/blob/d6f5cb22c82cab1a21a5367571b73632fe74e62a/lib/server/exashareresolver.py#L54)):_

> ``` Python
>                                        })
>                     else:
>                         result=[{'url': source['file']}]
> ```

This logic seems kinda flowed to me. Are you sure you wanna rewrite `result` on every iteration ?

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/kodi-czsk/script.module.stream.resolver/34)_

**Comment by lubo** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

_[lib/server/exashareresolver.py, line 40 [r1]](https://reviewable.io:443/reviews/kodi-czsk/script.module.stream.resolver/34#-KO-bS5W1IaIXLk_jm2X:-KO-bS5XRD-JRjuRFxcf:-1516607267) ([raw file](https://github.com/kodi-czsk/script.module.stream.resolver/blob/d6f5cb22c82cab1a21a5367571b73632fe74e62a/lib/server/exashareresolver.py#L40)):_

> ``` Python
>         data = data.group(1).decode('string_escape')
>         data = re.sub(r'\w+\(([^\)]+?)\)', r'\1', data) # Strip JS functions
>         data = re.sub(r''': *([^"'{\[][a-zA-Z]+)''',r':"\1"', data) # Fix incorrect JSON
> ```

What are these pairs of single quotes good for ? Shouldn't they be escaped ?

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/kodi-czsk/script.module.stream.resolver/34)_

**Comment by jose1711** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

_[lib/server/exashareresolver.py, line 40 [r1]](https://reviewable.io:443/reviews/kodi-czsk/script.module.stream.resolver/34#-KO-bS5W1IaIXLk_jm2X:-KO-cI5fP-JIZy2ml97g:-1390358900) ([raw file](https://github.com/kodi-czsk/script.module.stream.resolver/blob/d6f5cb22c82cab1a21a5367571b73632fe74e62a/lib/server/exashareresolver.py#L40)):_
afaik, ''' has the same effect as """.

```
>>> print ("""foo'bar".""")
foo'bar".
>>> print ('''foo'bar".''')
foo'bar".
```

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/kodi-czsk/script.module.stream.resolver/34)_

**Comment by lubo** [comment]
No activity for an extended period of time, closing.

**Pull request closed without merging**
