### PR TITLE
Add myvi.ru resolver

### PR DESCRIPTION
**Pull request by jose1711**
This change is [Reviewable](https://reviewable.io/reviews/kodi-czsk/script.module.stream.resolver/35)

### CODE REVIEW

**Comment by lubo** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

_[a discussion](https://reviewable.io:443/reviews/kodi-czsk/script.module.stream.resolver/35#-KNSoPMs7wjbn3-821wT:-KNSoPMs7wjbn3-821wU:1247095758) (no related file):_
All right, the logic here seems to be really flowed, but before any further discussion, could you run your code through a solid beautifier for once, please ? I can't read this shit !

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/kodi-czsk/script.module.stream.resolver/35)_

**Comment by jose1711** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

_[a discussion](https://reviewable.io:443/reviews/kodi-czsk/script.module.stream.resolver/35#-KNSoPMs7wjbn3-821wT:-KNTC5soRCqNmkvia2TB:-2085416333) (no related file):_
<details><summary>

<i>Previously, Kuci (Ľubomír Kučera) wrote…</i></summary>



> All right, the logic here seems to be really flowed, but before any further discussion, could you run your code through a solid beautifier for once, please ? I can't read this shit !
> </details>
> Ran it through PythonTidy, if a specific formatter is required, please advise.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/kodi-czsk/script.module.stream.resolver/35)_

**Comment by lubo** [comment]
Review status: 0 of 1 files reviewed at latest revision, 4 unresolved discussions.

---

_[a discussion](https://reviewable.io:443/reviews/kodi-czsk/script.module.stream.resolver/35#-KNSoPMs7wjbn3-821wT:-KNTYyD9V9Dv0OnKIafI:549971000) (no related file):_
<details><summary>

<i>Previously, jose1711 (Jose Riha) wrote…</i></summary>



> Ran it through PythonTidy, if a specific formatter is required, please advise.
> </details>
> Great. We want to follow PEP 8 but besides that, nothing special.

---

_[lib/server/myviruresolver.py, line 31 [r2]](https://reviewable.io:443/reviews/kodi-czsk/script.module.stream.resolver/35#-KNTZM-w73KKnoZhsHYF:-KNTZM-xiyDBJugP8qEx:417263867) ([raw file](https://github.com/kodi-czsk/script.module.stream.resolver/blob/84d240d1fcb441241d2b5f6f17219616dfe3661e/lib/server/myviruresolver.py#L31)):_

> ``` Python
> __name__ = 'myviru'
> 
> UA = 'Mozilla/6.0 (Windows; U; Windows NT 5.1; en-GB; rv:1.9.0.5) Gecko/2008092417 Firefox/3.0.3'
> ```

Why not to use `UA` from `util` ?

---

_[lib/server/myviruresolver.py, line 48 [r2]](https://reviewable.io:443/reviews/kodi-czsk/script.module.stream.resolver/35#-KNTZamEqgCUhnlr9w2g:-KNTZamEqgCUhnlr9w2h:1807415252) ([raw file](https://github.com/kodi-czsk/script.module.stream.resolver/blob/84d240d1fcb441241d2b5f6f17219616dfe3661e/lib/server/myviruresolver.py#L48)):_

> ``` Python
>     for f in playlist['video']:
>         streamurl = f['url']
>         streamurl += '|Cookie=' + urllib.quote('UniversalUserID='
> ```

Why do you always use `urllib.quote()` on `UniversalUserID=` ?  Hard coding `UniversalUserID%3D` instead would improve the performance a bit.

---

_[lib/server/myviruresolver.py, line 50 [r2]](https://reviewable.io:443/reviews/kodi-czsk/script.module.stream.resolver/35#-KNT_C0uQXQsxk9QbTAw:-KNT_C0uQXQsxk9QbTAx:-628187339) ([raw file](https://github.com/kodi-czsk/script.module.stream.resolver/blob/84d240d1fcb441241d2b5f6f17219616dfe3661e/lib/server/myviruresolver.py#L50)):_

> ``` Python
>         streamurl += '|Cookie=' + urllib.quote('UniversalUserID='
>             + uuid.value)
>         streamurl += '&User-Agent=' + urllib.quote(UA)
> ```

The same thing, but quoting the `UA` outside the loop would be more appropriate.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/kodi-czsk/script.module.stream.resolver/35)_

**Comment by jose1711** [comment]
Review status: 0 of 1 files reviewed at latest revision, 4 unresolved discussions.

---

_[a discussion](https://reviewable.io:443/reviews/kodi-czsk/script.module.stream.resolver/35#-KNSoPMs7wjbn3-821wT:-KNThfS70WAsdkqGi83r:1383441804) (no related file):_
<details><summary>

<i>Previously, Kuci (Ľubomír Kučera) wrote…</i></summary>



> Great. We want to follow PEP 8 but besides that, nothing special.
> </details>
> ok, will use autopep8 from now on, other suggestions implemented as well

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/kodi-czsk/script.module.stream.resolver/35)_

**Comment by lubo** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

_[a discussion](https://reviewable.io:443/reviews/kodi-czsk/script.module.stream.resolver/35#-KNSoPMs7wjbn3-821wT:-KNTlgqR32fQhfcpMOqm:-34646928) (no related file):_
<details><summary>

<i>Previously, jose1711 (Jose Riha) wrote…</i></summary>



> ok, will use autopep8 from now on, other suggestions implemented as well
> </details>
> But there's one exception you might want to know about. When it comes to line lengths, we use maximum of 100 characters.

LGTM, merging now.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/kodi-czsk/script.module.stream.resolver/35)_

**Comment by lubo** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/kodi-czsk/script.module.stream.resolver/35)_

**Pull request merged**
