### PR TITLE
Update flashx (using adopted modules from LordVenom/venom-xbmc-addons)

### PR DESCRIPTION
**Pull request by jose1711**
This is a somewhat twisted idea of importing LordVenom modules with minimum modifications and making a wrapper to make it work with the current logic of kodi-czsk's stream resolver. Keeping resolvers up to date with frequent site changes is a task LordVenom seem to tackle with ease. This commit unbreaks flashx resolvers but (for now) ignores subtitles. This will be fixed as soon as I'll stumble upon a video with subs.

### CODE REVIEW

**Comment by lubo** [comment]
If we really want to use LordVenom's resolvers, then maybe we should not import his code, but use his plugin instead. However, this is a big thing and we definitely should discuss it with @lzoubek first. When it comes to my opinion, I'll go for anything that may deliver better results than our own resolvers.

**Comment by jose1711** [comment]
Hmm... which plugin you're referring to? I think Libor is on vacation so this will need to wait a bit. Btw LordVenom still does not have support (and probably never will) for various sites we do.

**Comment by lubo** [comment]
AFAIK he's working on plugin.video.vstream only. I wanted to say we should add his plugin as a dependency to this plugin and use his resolvers when possible. But we'd have to add his plugin to our repo, which might not be cool.

**Comment by ghost** [comment]
najudržiavanejsi resolver je tento fork https://github.com/tknorris/script.module.urlresolver

**Comment by lubo** [comment]
Of course that it would be the best if somebody else was doing this for us. But I'm gonna close this PR because this particular patch set would embed 3rd party code into our plugin, so in the end of the day we would end up maintaining our own copy, which is exactly what we'd like to prevent.

**Pull request closed without merging**
